version: '2'
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: mysql:5.6.25
    environment:
      - MYSQL_ROOT_PASSWORD=noclip
    ports:
     - "3333:3306"
